# Generated by Django 4.1.7 on 2023-03-15 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 14, 21, 14, 17, 757285), verbose_name='Fecha de registro'),
        ),
    ]
