# Generated by Django 4.1.7 on 2023-03-15 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_employee_gender_alter_employee_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 14, 21, 24, 7, 736926), verbose_name='Fecha de registro'),
        ),
    ]
