# Generated by Django 4.1.7 on 2023-03-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_type_alter_employee_date_joined_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='categ',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
