# Generated by Django 4.1.7 on 2023-03-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_category_employee_categ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='names',
            new_name='name',
        ),
    ]
