# Generated by Django 4.1.7 on 2023-03-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_rename_names_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
    ]
